//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eap.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EapResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EapResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eap.Resource.EapResource", typeof(EapResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Backgroud {
            get {
                object obj = ResourceManager.GetObject("Backgroud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap BrownButtonDisable {
            get {
                object obj = ResourceManager.GetObject("BrownButtonDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap BrownButtonDown {
            get {
                object obj = ResourceManager.GetObject("BrownButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap BrownButtonUp {
            get {
                object obj = ResourceManager.GetObject("BrownButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ButtonDisable {
            get {
                object obj = ResourceManager.GetObject("ButtonDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ButtonDown {
            get {
                object obj = ResourceManager.GetObject("ButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ButtonExitBackground {
            get {
                object obj = ResourceManager.GetObject("ButtonExitBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ButtonExitMouseDown {
            get {
                object obj = ResourceManager.GetObject("ButtonExitMouseDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ButtonUp {
            get {
                object obj = ResourceManager.GetObject("ButtonUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Clean {
            get {
                object obj = ResourceManager.GetObject("Clean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap CloseButton {
            get {
                object obj = ResourceManager.GetObject("CloseButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap CurrentPosition {
            get {
                object obj = ResourceManager.GetObject("CurrentPosition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Eap_AppForm_frmChangePwd {
            get {
                object obj = ResourceManager.GetObject("Eap_AppForm_frmChangePwd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Eap_AppForm_frmDepartmentManage {
            get {
                object obj = ResourceManager.GetObject("Eap_AppForm_frmDepartmentManage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Eap_AppForm_frmFileManage {
            get {
                object obj = ResourceManager.GetObject("Eap_AppForm_frmFileManage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Eap_AppForm_frmLogQuery {
            get {
                object obj = ResourceManager.GetObject("Eap_AppForm_frmLogQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Eap_AppForm_frmMenuManage {
            get {
                object obj = ResourceManager.GetObject("Eap_AppForm_frmMenuManage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Eap_AppForm_frmServerProcessStatusQuery {
            get {
                object obj = ResourceManager.GetObject("Eap_AppForm_frmServerProcessStatusQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Eap_AppForm_frmSystemParameterManage {
            get {
                object obj = ResourceManager.GetObject("Eap_AppForm_frmSystemParameterManage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Eap_AppForm_frmUserManage {
            get {
                object obj = ResourceManager.GetObject("Eap_AppForm_frmUserManage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Eap_AppForm_frmValueListManage {
            get {
                object obj = ResourceManager.GetObject("Eap_AppForm_frmValueListManage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Feed {
            get {
                return ResourceManager.GetStream("Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap LoginHead {
            get {
                object obj = ResourceManager.GetObject("LoginHead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap MainLeftButton {
            get {
                object obj = ResourceManager.GetObject("MainLeftButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap MainLeftButtonDown {
            get {
                object obj = ResourceManager.GetObject("MainLeftButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap MainRightButton {
            get {
                object obj = ResourceManager.GetObject("MainRightButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap MainRightButtonDown {
            get {
                object obj = ResourceManager.GetObject("MainRightButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Menu {
            get {
                object obj = ResourceManager.GetObject("Menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Abide_AppForm_frmInStockTimeAbide {
            get {
                object obj = ResourceManager.GetObject("Mes_Abide_AppForm_frmInStockTimeAbide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Abide_AppForm_frmOrderAbide {
            get {
                object obj = ResourceManager.GetObject("Mes_Abide_AppForm_frmOrderAbide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Abide_AppForm_frmPaintOfflineTimeAbide {
            get {
                object obj = ResourceManager.GetObject("Mes_Abide_AppForm_frmPaintOfflineTimeAbide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Abide_AppForm_frmPaintOnlineTimeAbide {
            get {
                object obj = ResourceManager.GetObject("Mes_Abide_AppForm_frmPaintOnlineTimeAbide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Abide_AppForm_frmPaintOrderAbsoluteAbide {
            get {
                object obj = ResourceManager.GetObject("Mes_Abide_AppForm_frmPaintOrderAbsoluteAbide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Abide_AppForm_frmPaintOrderRelativeAbide {
            get {
                object obj = ResourceManager.GetObject("Mes_Abide_AppForm_frmPaintOrderRelativeAbide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Abide_AppForm_frmTrimOfflineTimeAbide {
            get {
                object obj = ResourceManager.GetObject("Mes_Abide_AppForm_frmTrimOfflineTimeAbide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Abide_AppForm_frmTrimOnlineTimeAbide {
            get {
                object obj = ResourceManager.GetObject("Mes_Abide_AppForm_frmTrimOnlineTimeAbide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Abide_AppForm_frmTrimOrderAbsoluteAbide {
            get {
                object obj = ResourceManager.GetObject("Mes_Abide_AppForm_frmTrimOrderAbsoluteAbide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Abide_AppForm_frmTrimOrderRelativeAbide {
            get {
                object obj = ResourceManager.GetObject("Mes_Abide_AppForm_frmTrimOrderRelativeAbide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Actual_AppForm_frmActualGraph {
            get {
                object obj = ResourceManager.GetObject("Mes_Actual_AppForm_frmActualGraph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Actual_AppForm_frmActualMoniter {
            get {
                object obj = ResourceManager.GetObject("Mes_Actual_AppForm_frmActualMoniter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Actual_AppForm_frmActualMoniterPassPoint {
            get {
                object obj = ResourceManager.GetObject("Mes_Actual_AppForm_frmActualMoniterPassPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Actual_AppForm_frmInStockRate {
            get {
                object obj = ResourceManager.GetObject("Mes_Actual_AppForm_frmInStockRate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Actual_AppForm_frmMonthProduceProgress {
            get {
                object obj = ResourceManager.GetObject("Mes_Actual_AppForm_frmMonthProduceProgress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Actual_AppForm_frmPaintDayBalance {
            get {
                object obj = ResourceManager.GetObject("Mes_Actual_AppForm_frmPaintDayBalance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Actual_AppForm_frmProduceMoniter {
            get {
                object obj = ResourceManager.GetObject("Mes_Actual_AppForm_frmProduceMoniter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Actual_AppForm_frmProduceProgress {
            get {
                object obj = ResourceManager.GetObject("Mes_Actual_AppForm_frmProduceProgress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Actual_AppForm_frmTrimDayBalance {
            get {
                object obj = ResourceManager.GetObject("Mes_Actual_AppForm_frmTrimDayBalance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Car_AppForm_frmAdvanceCarQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Car_AppForm_frmAdvanceCarQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Car_AppForm_frmAdvanceCarTimeSetup {
            get {
                object obj = ResourceManager.GetObject("Mes_Car_AppForm_frmAdvanceCarTimeSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Car_AppForm_frmCarBroken {
            get {
                object obj = ResourceManager.GetObject("Mes_Car_AppForm_frmCarBroken", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Car_AppForm_frmCarDetail {
            get {
                object obj = ResourceManager.GetObject("Mes_Car_AppForm_frmCarDetail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Car_AppForm_frmCarFlagQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Car_AppForm_frmCarFlagQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Car_AppForm_frmCarFlagSetup {
            get {
                object obj = ResourceManager.GetObject("Mes_Car_AppForm_frmCarFlagSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Car_AppForm_frmCarInfoWarningCM7 {
            get {
                object obj = ResourceManager.GetObject("Mes_Car_AppForm_frmCarInfoWarningCM7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Car_AppForm_frmCarMove {
            get {
                object obj = ResourceManager.GetObject("Mes_Car_AppForm_frmCarMove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Car_AppForm_frmCarQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Car_AppForm_frmCarQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Car_AppForm_frmDelayCarQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Car_AppForm_frmDelayCarQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Car_AppForm_frmDelayCarTimeSetup {
            get {
                object obj = ResourceManager.GetObject("Mes_Car_AppForm_frmDelayCarTimeSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Car_AppForm_frmStopCarQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Car_AppForm_frmStopCarQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Device_AppForm_frmPrinterManage {
            get {
                object obj = ResourceManager.GetObject("Mes_Device_AppForm_frmPrinterManage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Oee_AppForm_frmFixedStop {
            get {
                object obj = ResourceManager.GetObject("Mes_Oee_AppForm_frmFixedStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Oee_AppForm_frmPaintLineStopMaintain {
            get {
                object obj = ResourceManager.GetObject("Mes_Oee_AppForm_frmPaintLineStopMaintain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Oee_AppForm_frmPaintOEE {
            get {
                object obj = ResourceManager.GetObject("Mes_Oee_AppForm_frmPaintOEE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Oee_AppForm_frmTrimLineStopMaintain {
            get {
                object obj = ResourceManager.GetObject("Mes_Oee_AppForm_frmTrimLineStopMaintain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Oee_AppForm_frmTrimOEE {
            get {
                object obj = ResourceManager.GetObject("Mes_Oee_AppForm_frmTrimOEE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Paint_AppForm_frmCheckOneScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Paint_AppForm_frmCheckOneScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Paint_AppForm_frmCheckTwoScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Paint_AppForm_frmCheckTwoScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Paint_AppForm_frmElectrophoresisScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Paint_AppForm_frmElectrophoresisScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Paint_AppForm_frmMachineFinishScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Paint_AppForm_frmMachineFinishScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Paint_AppForm_frmMachineMidScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Paint_AppForm_frmMachineMidScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Paint_AppForm_frmMachinePvcScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Paint_AppForm_frmMachinePvcScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Paint_AppForm_frmMidPolishScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Paint_AppForm_frmMidPolishScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Paint_AppForm_frmPaintCarSeries {
            get {
                object obj = ResourceManager.GetObject("Mes_Paint_AppForm_frmPaintCarSeries", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Paint_AppForm_frmPaintColor {
            get {
                object obj = ResourceManager.GetObject("Mes_Paint_AppForm_frmPaintColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Paint_AppForm_frmPaintOfflineScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Paint_AppForm_frmPaintOfflineScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Paint_AppForm_frmPaintOnline {
            get {
                object obj = ResourceManager.GetObject("Mes_Paint_AppForm_frmPaintOnline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Paint_AppForm_frmSealantOneScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Paint_AppForm_frmSealantOneScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Paint_AppForm_frmSealantTwoScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Paint_AppForm_frmSealantTwoScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Paint_AppForm_frmSkirtSideGlueScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Paint_AppForm_frmSkirtSideGlueScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Pbs_AppForm_frmContinueSetup {
            get {
                object obj = ResourceManager.GetObject("Mes_Pbs_AppForm_frmContinueSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Pbs_AppForm_frmDirectCarSetup {
            get {
                object obj = ResourceManager.GetObject("Mes_Pbs_AppForm_frmDirectCarSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Pbs_AppForm_frmIntervalSetup {
            get {
                object obj = ResourceManager.GetObject("Mes_Pbs_AppForm_frmIntervalSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Pbs_AppForm_frmPbsControlSetup {
            get {
                object obj = ResourceManager.GetObject("Mes_Pbs_AppForm_frmPbsControlSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Pbs_AppForm_frmPbsGroupInPriority {
            get {
                object obj = ResourceManager.GetObject("Mes_Pbs_AppForm_frmPbsGroupInPriority", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Pbs_AppForm_frmPbsGroupSetup {
            get {
                object obj = ResourceManager.GetObject("Mes_Pbs_AppForm_frmPbsGroupSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Pbs_AppForm_frmPbsLaneDeviceConfig {
            get {
                object obj = ResourceManager.GetObject("Mes_Pbs_AppForm_frmPbsLaneDeviceConfig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Pbs_AppForm_frmPbsOnline1Ex {
            get {
                object obj = ResourceManager.GetObject("Mes_Pbs_AppForm_frmPbsOnline1Ex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Pbs_AppForm_frmPbsOutTravelQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Pbs_AppForm_frmPbsOutTravelQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Pbs_AppForm_frmPbsSignal1Ex {
            get {
                object obj = ResourceManager.GetObject("Mes_Pbs_AppForm_frmPbsSignal1Ex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Pbs_AppForm_frmPbsSpecialCarColorSetup {
            get {
                object obj = ResourceManager.GetObject("Mes_Pbs_AppForm_frmPbsSpecialCarColorSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Pbs_AppForm_frmPbsSpecialCarLineSetup {
            get {
                object obj = ResourceManager.GetObject("Mes_Pbs_AppForm_frmPbsSpecialCarLineSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Pbs_AppForm_frmShortPartSetup {
            get {
                object obj = ResourceManager.GetObject("Mes_Pbs_AppForm_frmShortPartSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Pbs_AppForm_frmTrimModelPriority {
            get {
                object obj = ResourceManager.GetObject("Mes_Pbs_AppForm_frmTrimModelPriority", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Plan_AppForm_frmCarProjectPlanModify {
            get {
                object obj = ResourceManager.GetObject("Mes_Plan_AppForm_frmCarProjectPlanModify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Plan_AppForm_frmDayPlanQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Plan_AppForm_frmDayPlanQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Plan_AppForm_frmMonthPlanQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Plan_AppForm_frmMonthPlanQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Plan_AppForm_frmNoPlanOrderQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Plan_AppForm_frmNoPlanOrderQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Plan_AppForm_frmWeekPlanQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Plan_AppForm_frmWeekPlanQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Produce_AppForm_frmModuleDayPlan {
            get {
                object obj = ResourceManager.GetObject("Mes_Produce_AppForm_frmModuleDayPlan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Produce_AppForm_frmModuleHourConfig {
            get {
                object obj = ResourceManager.GetObject("Mes_Produce_AppForm_frmModuleHourConfig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Produce_AppForm_frmModuleHourProduce {
            get {
                object obj = ResourceManager.GetObject("Mes_Produce_AppForm_frmModuleHourProduce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Produce_AppForm_frmModulePrint {
            get {
                object obj = ResourceManager.GetObject("Mes_Produce_AppForm_frmModulePrint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Produce_AppForm_frmSynchroAgainSend {
            get {
                object obj = ResourceManager.GetObject("Mes_Produce_AppForm_frmSynchroAgainSend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Produce_AppForm_frmSynchroClient {
            get {
                object obj = ResourceManager.GetObject("Mes_Produce_AppForm_frmSynchroClient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Produce_AppForm_frmSynchroClientStatus {
            get {
                object obj = ResourceManager.GetObject("Mes_Produce_AppForm_frmSynchroClientStatus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmAbnormalMaintain {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmAbnormalMaintain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmCartypePartQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmCartypePartQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmCheckLineFinishScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmCheckLineFinishScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmCheckLinePopScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmCheckLinePopScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmConfigQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmConfigQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmDebugFinishScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmDebugFinishScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmDebugOfflinePopScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmDebugOfflinePopScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmEngine1Scan {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmEngine1Scan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmEngineNoModify {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmEngineNoModify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmOffline1Scan {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmOffline1Scan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmOfflinePop1Scan {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmOfflinePop1Scan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmProduceDepartmentOrder {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmProduceDepartmentOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmProduceTagBatchModify {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmProduceTagBatchModify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmProduceTagCarTypePart {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmProduceTagCarTypePart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmProduceTagCodeManage {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmProduceTagCodeManage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmProduceTagManage {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmProduceTagManage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmProduceTagModify {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmProduceTagModify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmProduceTagPrintQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmProduceTagPrintQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmReturnCarQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmReturnCarQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmReturnItemQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmReturnItemQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmReturnOrder {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmReturnOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmRoadTestPopScan {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmRoadTestPopScan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmSalesReturnInStock {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmSalesReturnInStock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmTrimIn1Scan {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmTrimIn1Scan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Trim_AppForm_frmWorkshopRecvOrder {
            get {
                object obj = ResourceManager.GetObject("Mes_Trim_AppForm_frmWorkshopRecvOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Work_AppForm_frmLineStandardSetup {
            get {
                object obj = ResourceManager.GetObject("Mes_Work_AppForm_frmLineStandardSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Work_AppForm_frmLineStatusQuery {
            get {
                object obj = ResourceManager.GetObject("Mes_Work_AppForm_frmLineStatusQuery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Mes_Work_AppForm_frmWorkCalendarSetup {
            get {
                object obj = ResourceManager.GetObject("Mes_Work_AppForm_frmWorkCalendarSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap MinimizeButton {
            get {
                object obj = ResourceManager.GetObject("MinimizeButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap OEE管理 {
            get {
                object obj = ResourceManager.GetObject("OEE管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream PassSound {
            get {
                return ResourceManager.GetStream("PassSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap PBS控制一期 {
            get {
                object obj = ResourceManager.GetObject("PBS控制一期", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Return {
            get {
                object obj = ResourceManager.GetObject("Return", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Revise {
            get {
                object obj = ResourceManager.GetObject("Revise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap Service {
            get {
                object obj = ResourceManager.GetObject("Service", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SubLeftButton {
            get {
                object obj = ResourceManager.GetObject("SubLeftButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SubLeftButtonDown {
            get {
                object obj = ResourceManager.GetObject("SubLeftButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SubRightButton {
            get {
                object obj = ResourceManager.GetObject("SubRightButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap SubRightButtonDown {
            get {
                object obj = ResourceManager.GetObject("SubRightButtonDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WarningSound {
            get {
                return ResourceManager.GetStream("WarningSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WarningSound1 {
            get {
                return ResourceManager.GetStream("WarningSound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 作业管理 {
            get {
                object obj = ResourceManager.GetObject("作业管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 总装控制一期 {
            get {
                object obj = ResourceManager.GetObject("总装控制一期", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 涂装控制一期 {
            get {
                object obj = ResourceManager.GetObject("涂装控制一期", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 生产实绩 {
            get {
                object obj = ResourceManager.GetObject("生产实绩", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 生产指示 {
            get {
                object obj = ResourceManager.GetObject("生产指示", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 生产计划 {
            get {
                object obj = ResourceManager.GetObject("生产计划", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 系统管理 {
            get {
                object obj = ResourceManager.GetObject("系统管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 设备管理 {
            get {
                object obj = ResourceManager.GetObject("设备管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 车辆管理 {
            get {
                object obj = ResourceManager.GetObject("车辆管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 遵守率管理 {
            get {
                object obj = ResourceManager.GetObject("遵守率管理", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
